
--VERIDICA SE EXISTE PROCEDURE JA CRIADA NA BASE DE DADOS
--SE HOUVER, IRA APAGAR E CRIAR NOVAMENTE
IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE TYPE ='P' AND NAME = 'SP_CONSULTAR_CLIENTES')
BEGIN
	DROP PROCEDURE SP_CONSULTAR_CLIENTES
END
GO
